# Generated by Django 5.1.4 on 2025-01-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField(max_length=100)),
                ('mathematics', models.IntegerField(max_length=100)),
                ('physics', models.IntegerField(max_length=100)),
                ('chemistry', models.IntegerField(max_length=100)),
                ('biology', models.IntegerField(max_length=100)),
                ('business', models.IntegerField(max_length=100)),
                ('agriculture', models.IntegerField(max_length=100)),
                ('computer', models.IntegerField(max_length=100)),
                ('history', models.IntegerField(max_length=100)),
                ('geography', models.IntegerField(max_length=100)),
                ('christian', models.IntegerField(max_length=100)),
                ('french', models.IntegerField(max_length=100)),
                ('Islamic', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('administration_number', models.IntegerField(max_length=6)),
                ('lower_school', models.CharField(max_length=100)),
                ('Guardians', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.subjects')),
            ],
        ),
    ]
