# Generated by Django 5.1.4 on 2025-01-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_subjects_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='school',
        ),
        migrations.AddField(
            model_name='tutors',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
